num1= int (input("Enter first number: "))
num2= int (input("Enter second number: "))
sum= (num1+num2)        
sub= (num1-num2)
mul= (num1*num2)        
div = (num1/num2)   
print("Sum is: ", sum)
print("Subtraction is: ", sub)  
print("Multiplication is: ", mul)
print("Division is: ", div)